name: quitanda_com_getx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit:
  mask_text_input_formatter:
  badges: ^2.0.3
  intl: ^0.18.0
  add_to_cart_animation: ^2.0.3
  fluttertoast: ^8.1.2
  shimmer: ^2.0.0
  get: ^4.6.5
  dio: ^4.0.6
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.3
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  flutter_secure_storage: ^7.0.1
  clipboard: ^0.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fruits/
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true